name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger
    inputs:
      commit_sha:
        description: 'Commit SHA to build from (optional)'
        required: false
        default: ''

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.commit_sha || github.sha }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Playwright browsers
      run: |
        playwright install chromium
        
    - name: Build Windows executable
      run: |
        python build_windows.py
        
    - name: Check if executable was created
      run: |
        if (Test-Path "dist/Meulade_RVSQ.exe") {
          Write-Host "Executable created successfully!"
          $size = (Get-Item "dist/Meulade_RVSQ.exe").Length / 1MB
          Write-Host "File size: $([math]::Round($size, 2)) MB"
        }
        else {
          Write-Host "Executable not found!"
          exit 1
        }
      shell: pwsh
        
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: Meulade_RVSQ-Windows-x64
        path: dist/Meulade_RVSQ.exe
        retention-days: 30
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/Meulade_RVSQ.exe
        name: Meulade_RVSQ ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
